# Study Details

## Study Design

ECHOES is a fully online study that recruited entirely from Prolific. ECHOES was designed to get a relatively large sample size (target N = 400) with a brief protocol (~30 minutes). It is a cross-sectional study with 1 timepoint. Trhough Prolific, an equal number of male and female participants were recruited, and a ratio of White/non-White participants consistent with the United States population of young adults (212/400 or 53% White, 188/400 or 47% non-White). 

## Questionnaires

Questionnaires are listed below in the order they were administered to participants: 

* __Demographics__
    + BAB Lab
* __Visceral Sensitivity Index (vsi)__
    + Adapted by FQ and BC from: Labus JS, Bolus R, Chang L, Wiklund I, Naesdal J, Mayer EA, Naliboff BD. The Visceral Sensitivity Index: development and validation of a gastrointestinal symptom-specific anxiety scale. Aliment Pharmacol Ther. 2004 Jul 1;20(1):89-97. doi: 10.1111/j.1365-2036.2004.02007.x. PMID: 15225175.
* __Rome IV IBS criteria (rome)__
    + BAB Lab
* __Patient Health Questionnaire, Depression Module (PHQ-9)__
    + Kroenke, K., Spitzer, R.L. & Williams, J.B.W. The PHQ-9. J GEN INTERN MED 16, 606–613 (2001). https://doi.org/10.1046/j.1525-1497.2001.016009606.x
* __Generalized Anxiety Disorder 7 (GAD-7)__
    + Spitzer RL, Kroenke K, Williams JBW, Löwe B. A Brief Measure for Assessing Generalized Anxiety Disorder: The GAD-7. Arch Intern Med. 2006;166(10):1092–1097. doi:10.1001/archinte.166.10.1092
* __Somatic Symptoms (PHQ-15)__
    + Korber S, Frieser D, Steinbrecher N, & Hiller, W. Classification characteristics of the Patient Health Questionnaire-15 for screening somatoform disorders in a primary care setting. Journal of Psychosomatic Research. 2011;71(3). https://doi.org/10.1016/j.jpsychores.2011.01.006
* __Chronic Pain__
    + Created by BAB Lab based on the following 2 sources:
    + Deyo RA, Dworkin SF, Amtmann D, Andersson G, Borenstein D, Carragee E, Carrino J, Chou R, Cook K, DeLitto A, Goertz C, Khalsa P, Loeser J, Mackey S, Panagis J, Rainville J, Tosteson T, Turk D, Von Korff M, Weiner DK. Report of the NIH Task Force on research standards for chronic low back pain. J Pain. 2014 Jun;15(6):569-85. doi: 10.1016/j.jpain.2014.03.005. Epub 2014 Apr 29. PMID: 24787228; PMCID: PMC4128347.
    + Dahlhamer J, Lucas J, Zelaya C, Nahin R, Mackey S, DeBar L, Kerns R, Von Korff M, Porter L, Helmick C. Prevalence of Chronic Pain and High-Impact Chronic Pain Among Adults - United States, 2016. MMWR Morb Mortal Wkly Rep. 2018 Sep 14;67(36):1001-1006. doi: 10.15585/mmwr.mm6736a2. PMID: 30212442; PMCID: PMC6146950.
* __Brief Resilient Coping Scale (BRCS)__
    + Sinclair VG, Wallston KA. The development and psychometric evaluation of the Brief Resilient Coping Scale. Assessment. 2004 Mar;11(1):94-101. doi: 10.1177/1073191103258144. PMID: 14994958.
* __Multidimensional Scale of Perceived Social Support (MSPSS)__
    + Gregory D. Zimet , Suzanne S. Powell , Gordon K. Farley , Sidney Werkman & Karen A. Berkoff (1990) Psychometric Characteristics of the Multidimensional Scale of Perceived Social Support, Journal of Personality Assessment, 55:3-4, 610-617, DOI: 10.1080/00223891.1990.9674095
* __Mental Health Continuum Short Form (MHC-SF)__
    + Lamers S, Westerhof G, Bohlmeijer P, ten Klooster P, Keyes, C. Evaluating the psychometric properties of the mental health Continuum-Short Form (MHC-SF). Journal of Clinical Psychology. 2010.  https://doi.org/10.1002/jclp.20741. 
* __Toronoto Alexithymia Scale (external thinking subscale removed)__
    + R.Michael Bagby, James D.A. Parker, Graeme J. Taylor. The twenty-item Toronto Alexithymia scale—I. Item selection and cross-validation of the factor structure. Journal of Psychosomatic Research. 1994:38(1).https://doi.org/10.1016/0022-3999(94)90005-1.
* __Childhood Trauma Questionnaire Short Form (CTQ-SF)__
    + Hagborg JM, Kalin T, Gerdner A. The Childhood Trauma Questionnaire-Short Form (CTQ-SF) used with adolescents - methodological report from clinical and community samples. J Child Adolesc Trauma. 2022 Mar 30;15(4):1199-1213. doi: 10.1007/s40653-022-00443-8. PMID: 36439669; PMCID: PMC9684390.
* __Questionnaire of Unpredictabiltiy in Childhood - Brief Version (QUIC-5)__
    + Lindert N, Maxwell M, Liu S, Stern H, Baram T, Davis E, Risbrough V, Baker D, Nievergell C, Glynn L. Exposure to unpredictability and mental health: Validation of the brief version of the Questionnaire of Unpredictability in Childhood (QUIC-5) in English and Spanish. Frontiers in Psychology. 2022:13. https://doi.org/10.3389/fpsyg.2022.971350. 
* __Assessment of Parent and Child Adversity (APCA)__
    + Edited by BAB Lab for adult respondents to capture childhood, adolescence, adulthood, and current occurances of stressful life events. 
    + King LS, Humphreys KL, Shaw GM, Stevenson DK, Gotlib IH. Validation of the Assessment of Parent and Child Adversity (APCA) in Mothers and Young Children. J Clin Child Adolesc Psychol. 2023 Sep 3;52(5):686-701. doi: 10.1080/15374416.2022.2042696. Epub 2022 May 2. PMID: 35500216; PMCID: PMC9626394.
* __Perceived Stress Scale (PSS)__ 
    + Cohen, S., Kamarck, T., & Mermelstein, R. (1983). A Global Measure of Perceived Stress. Journal of Health and Social Behavior, 24(4), 385–396. https://doi.org/10.2307/2136404

## Study Contributions

FQ and BC designed study. FQ and GF collected data. FQ and GF (so far) carried out analysis. 

## Funding

ECHOES was funded through BC's startup fund from UCLA. 